### ISSUE TITLE
Finer Granularity in Rect Hit Box Mouse Clicks

### ISSUE THREAD

**Issue by ArikVhedrovix** [Deep-Phield-Softworks/XeroSum#15]
While tests for clicking inside a Tile object are handled, the other types of Matter subclasses need a per pixel click determination code. I plan to use the pygame.surface.get_at((px,py)) method along with the (px,py) of the hit box pygame.Rect object to determine if the color values of the clicked on pixel are equal to the values of the COLORKEY for transparent portions of images.

**Comment by EricFedrowisch** [comment]
Done in theory.
