### ISSUE TITLE
aoe.py needs more work

### ISSUE THREAD

**Issue by ArikVhedrovix** [Deep-Phield-Softworks/XeroSum#41]
-make_n_dimensional method is not intuitive and only works up to 3 dimensions
-really need a recursive algorithm to make arbitrary number of dimensions for it to work as advertised
-comments are jacked up
-probably should require it to only take an iterable as input for the size of the dimensions.

**Comment by CToups** [comment]
While doing general code cleanup, I will pay special attention to aoe.py and see if I can make things simpler. Though I probably won't be adding your recursive algorithm.

**Comment by EricFedrowisch** [comment]
Link for future Triangle Shape class:
http://totologic.blogspot.fr/2014/01/accurate-point-in-triangle-test.html

**Comment by EricFedrowisch** [comment]
Done with basic rewrite. Only usable shape written atm is Cuboid. I removed Square and will likely only write 3D shapes in the future as I can't think of a use case for a 2D shape.
Probably need another layer that checks LOS to exclude points in a shape that are "underground" or "behind a wall" or whatever.
Future shapes:
-Sphere
-Cone

**Comment by EricFedrowisch** [comment]
Busting the remaining tasks out to separate issues.
