### ISSUE TITLE
Game State/Controls module

### ISSUE THREAD

**Issue by ArikVhedrovix** [Deep-Phield-Softworks/XeroSum#50]
We need a module that stores the state of the overall game and records changes. These changes include but are not limited to:
-Game Time Paused/ Running
-What windows are opened(Inventory, Game Menu, etc)
-Squad order queues
-What objects need to be ticked
This module should also receive user input game events and process those and any changes to state they may cause.

**Comment by EricFedrowisch** [comment]
I feel that most of the systems in the comments above should be broken down into separate issues of their own. Since controller.py is written I am gonna close this issue and open the others.
