### ISSUE TITLE
Effect Class

### ISSUE THREAD

**Issue by ArikVhedrovix** [Deep-Phield-Softworks/XeroSum#52]
Before Weapons and Items can be made meaningful;
An Effect class is needed. 
Effects should have the following attributes:
-Effects can recursively contain other Effects
As an example: A grenade may apply an Effect that contains a damage Effect with type explosion and a damage Effect with type slashing (from fragmentation)
-Effects do not internally store Area of Effect information. That should be stored/implemented at the Effect applicator level.
-Effects are only responsible for informing objects of the Effect attributes. Objects must implement a meaningful response to being informed of an effect. (An Entity would only be informed it received a damage Effect of type fire and magnitude 10. It is up to the Entity to decrement Hit Points.)
-Effects should have self.duration, self.tick_accumulator and self.tick_threshold. (self.duration == 0 means instant)
(Poison might have a duration of a few minutes and give periodic damage equal to its magnitude every time the tick accumulator is greater than the threshold)
-Effects should have boolean self.container that returns True if they contain other Effects.
-Effects should have a method to return a list of their information in the format:
[(type,magnitude), ... ]. This list will have only one entry in Non-Container Effects.
-Effects should have a method yield_effects that can be called either by a container that contains them or from outside any Effects objects to yield all the sum of Effects in the list format. 
-If an Effect is not a container for other Effects it will have the following attributes:  
self.type = string, self.magnitude = integer, self.container = False
-If an Effect is a container it will have only self.container = True

**Comment by EricFedrowisch** [comment]
First write of Effect class done. See effect.py for implementation details as they are not exactly as the outline above.
