### ISSUE TITLE
Render Rewrite

### ISSUE THREAD

**Issue by ArikVhedrovix** [Deep-Phield-Softworks/XeroSum#59]
Each render cycle, make a hash from operator.itemgetter( ) and test to see if it is in an ZODB OOBTree. Add it if it doesn't already exist. This will automatically sort the render elements. When an element moves, use its old entry to get the collisions to redraw. Take those collisions and sort them using the current sorting method. Then remove the old entry and store a hash using its new attributes. I think this means we will have to iterate over each element only twice per render cycle instead of three times and using dirty rectangle blitting will be much more efficient in redrawing the screen. The collision/dirty redraw will require some more processing, but hopefully less than the third full element iteration plus redrawing every element every cycle. I should also use a second OOBTree for the dirty elements so that they will be sorted as they are entered.

**Comment by EricFedrowisch** [comment]
The planned rewrite has been implemented.
