### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by CToups** [Deep-Phield-Softworks/XeroSum#65]
Much code needs to be cleaned up. Simple things like making multi-line comments multi-line comments instead of a bunch of single line comments. This will take place in many different files.

**Comment by EricFedrowisch** [comment]
I want to go back to putting each self.accepted_kwarg key value pair on a separate line. I feel this imporves readability. There is a problem with my IDE that I use that makes it display these multi-line variables improperly. I will be manually editing them to satisfy PEP8 compliance as needed.

**Comment by EricFedrowisch** [comment]
I think the first pass can be called finished and a success! Good work everyone!
